# Generated by Django 5.2.1 on 2025-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_alter_video_options_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_120p',
            field=models.FileField(blank=True, null=True, upload_to='videos/120p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
    ]
