# Generated by Django 5.2.1 on 2025-06-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0003_video_file_1080p_video_file_120p_video_file_360p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
