# Generated by Django 5.2.1 on 2025-07-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0004_video_hls_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_120p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_360p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_720p',
        ),
    ]
